# -*- coding: utf-8 -*-
"""Entrega 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16gH8nw_RgXiDMAppOECOrZHnhEJizt06
"""

"""
Module containing the actual Decision Tree for the topic of the project.
"""

import pandas as pd
import math
import python_utils

 Data=pd.read_csv("data_set.csv")
  Data=Data[["ph", "soil_temperature", "soil_moisture", "illuminance", "env_temperature","env_humidity","label"]]
  """"
  Title:<Github.com>
  Author:geerk
  Date:<2019>
  Code Version: 20 Mar 2012
  Availability:https://github.com/geerk/C45algorithm/blob/master/c45.py
    
  """

def info(Data, res_col):
   
    s = 0 # sum
    for v in utils.deldup(Data[res_col]):
        p = freq(Data, res_col, v) / float(len(Data[res_col]))
        s += p * math.log(p, 2)
    return -s
  
 def infox(Data, col, res_col):
   
    s = 0 # sum
    for subt in utils.get_subtables(Data, col):
        s += (float(len(subt[col])) / len(Data[col])) * info(subt, res_col)
    return s
  
  def gain(Data, x, res_col):
   
    return info(Data, res_col) - infox(Data, x, res_col)